name: Medication Reminder Cron

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  call-reminder-api:
    runs-on: ubuntu-latest
    steps:
            - name: Call sendReminder endpoint
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://medication-reminder-sand.vercel.app/api/sendReminder)
          echo "HTTP status: $STATUS"
          if [ "$STATUS" -ne 200 ]; then exit 1; fi

